tests/TodoApp.Tests/TodoAppFixture.cs
tests/TodoApp.Tests/testsettings.json

Fix configuration by not clearing sources, which was causing `UseUrls()` and any other changes made to the host being lost.
Explicitly set `EnterpriseDomain` to empty so my local secrets.json changes don't overwrite in in the tests without having to try and inspect the sources and manually remove user secrets.

Fix test configuration

---

src/TodoApp/ApiModule.cs
src/TodoApp/AuthenticationModule.cs
src/TodoApp/Extensions/OpenApiEndpointConventionBuilderExtensions.cs
src/TodoApp/Program.cs

* The `IHostEnvironment` parameter isn't used, so remove it.
* Add TODO comments for code that can be removed when ASP.NET Core and/or Swashbuckle changes are available to be consumed.
* Add braces to API method make the code a bit more readable.

Refactoring

---

src/TodoApp/ApiModule.cs
src/TodoApp/AuthenticationModule.cs
src/TodoApp/Extensions/OpenApiEndpointConventionBuilderExtensions.cs

Refactor the extensions for OpenAPI metadata to match proposed future API that will be built-in to ASP.NET Core to do the same thing.

Refactor OpenAPI extensions

---

src/TodoApp/scripts/ts/view/TodoApp.ts
src/TodoApp/scripts/ts/view/TodoElement.ts

Refresh the text for a relative timestamp on a Todo item every 30 seconds.

Keep relative timestamps current

---

Directory.Build.props
tests/TodoApp.Tests/HttpServerFixture.cs
tests/TodoApp.Tests/TodoAppFixture.cs

Refactor the workaround for issue with `CreateHostBuilder()` returning `null` with minimal hosting by creating the server in `CreateHost()` instead.

Refactor WebApplicationFactory<T> Usage

---

tests/TodoApp.Tests/HttpServerFixture.cs

Only call `CreateDefaultClient()` if the host has not been created yet.

Only call CreateDefaultClient once

---

global.json
src/TodoApp/ApiModule.cs
src/TodoApp/AuthenticationModule.cs
src/TodoApp/Extensions/OpenApiEndpointConventionBuilderExtensions.cs
tests/TodoApp.Tests/UITests.cs

* Update to the latest .NET 6 RC1 SDK.
* Update the extension methods for OpenAPI metadata to match the latest proposed API for doing so.
* Wait half a second in test before checking the number of items to give the UI time to update.

Update SDK and OpenAPI extensions

---

src/TodoApp/ApiModule.cs
src/TodoApp/AuthenticationModule.cs
src/TodoApp/Program.cs
src/TodoApp/TodoApp.csproj

- Close over WebApplicationBuilder for configuration and environment.
- Male explicit call to UseRouting so the error handler works
- Grouped middleware Use* before route Map*.

Small tweaks to application setup

---

Directory.Build.props

The reference to `Microsoft.Net.Compilers.Toolset` is no longer needed with Visual Studio 2022 Preview 3 as it now understands file-scoped namespaces.

Remove Microsoft.Net.Compilers.Toolset

---

.vscode/launch.json

* Forward secrets from Codespaces for OAuth.
* Use the `workspaceFolder` variable instead of `workspaceRoot` ([docs](https://code.visualstudio.com/docs/editor/variables-reference#_why-isnt-workspaceroot-documented)).

Forward secrets

---

.devcontainer/devcontainer.json

Run build when the container is created to install the .NET SDK.

Run build on container creation

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
build.ps1
src/TodoApp/Pages/_ViewImports.cshtml
src/TodoApp/Program.cs

* Use the universal container for GitHub Codespaces.
* Use `NUGET_PACKAGES` for the NuGet global package cache if it is set.
* Launch port 5000 and ignore port 5001.
* Add tag helpers to the Razor Pages.
* Allow HTTP outside of production.

Use universal Codespaces container

---

.devcontainer/devcontainer.json
.vscode/launch.json
README.md
src/TodoApp/AuthenticationModule.cs
src/TodoApp/Pages/Home/Index.cshtml
src/TodoApp/Pages/Shared/_Layout.cshtml
src/TodoApp/Program.cs
tests/TodoApp.Tests/ApiTests.cs

* Change the path used to sign in as GitHub Codespaces seems to reserve `/signin`.
* Fix OAuth not working by configuring [nginx correctly for forwarded headers](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer#forward-the-scheme-for-linux-and-non-iis-reverse-proxies), including ensuring the `Host` is also forwarded so the redirect URI is correct.
* Configure port 5001 to be used by default.

Fixes for Codespaces

---

.github/dependabot.yml

Disable NuGet package updates until the stable .NET 6 RC1 build is released.

Disable NuGet updates

---

src/TodoApp/TodoApp.csproj

Fix HTTP 404s caused by Razor Views not being compiled into the application after SDK update when using Visual Studio.

Fix HTTP 404s in Visual Studio

---

.github/dependabot.yml
.github/workflows/update-dotnet-sdk.yml
NuGet.config
README.md
global.json
src/TodoApp/TodoApp.csproj

* Update to the official release candidate 1 build for .NET 6.
* Re-enable dependabot updates.
* Re-enable .NET SDK updates.

Update to .NET 6 RC1 

---

tests/TodoApp.Tests/BrowserFixture.cs
tests/TodoApp.Tests/BrowserFixtureOptions.cs
tests/TodoApp.Tests/UITests.cs

Apply some of the refactoring from https://github.com/martincostello/dotnet-playwright-tests to the test fixture used in the sample.
The BrowserStack support hasn't been added as it doesn't work with a `127.0.0.1` IP address (instead of `localhost`) which the app uses as part of its local TLS testing. Maybe that can be refactored/changed in the future, but leaving as-is for now.

Refactor UI tests

---

tests/TodoApp.Tests/BrowserFixture.cs
tests/TodoApp.Tests/BrowserFixtureOptions.cs
tests/TodoApp.Tests/BrowserStackLocalOptions.cs
tests/TodoApp.Tests/BrowserStackLocalService.cs

Add support for optional testing with BrowserStack Automate, which incorporates the use of [Local Testing](https://www.browserstack.com/local-testing/automate).

Support BrowserStack Automate

---

tests/TodoApp.Tests/BrowserFixture.cs

BrowserStack Automate now supports Playwright 1.18.1, so tracing now works.

Enable tracing with BrowserStack Automate

---

src/TodoApp/gulpfile.js

Fix running `default` causing a circular dependency with `watch` when formatting was run which would make it build (and format) again.

Fix circular dependency

---

tests/TodoApp.Tests/HttpServerFixture.cs

`TestServer` _shouldn't_ need to be used, and according to #866 not doing so should speed things up.

Do not start TestServer

---

src/TodoApp/package-lock.json

Bump elliptic to 6.5.7 to resolve vulnerability alert.

Bump elliptic

---

.vscode/launch.json
.vsconfig
Directory.Build.props
README.md
TodoApp.ruleset
build.ps1
global.json
src/TodoApp/Program.cs
src/TodoApp/TodoApp.csproj
src/TodoApp/wwwroot/swagger-ui/index.html
startvscode.cmd
tests/TodoApp.Tests/HttpServerFixture.cs
tests/TodoApp.Tests/TodoApp.Tests.csproj

- Update to ASP.NET Core 9.
- Replace NSwag with Microsoft.AspNetCore.OpenApi.
- Fix/suppress new code analysis warnings.

Update to ASP.NET Core 9

---

tests/TodoApp.Tests/ApiTests.cs
tests/TodoApp.Tests/TodoApp.Tests.csproj
tests/TodoApp.Tests/UITests.cs

Migrate to xunit v3

---

tests/TodoApp.Tests/ApiTests.cs

Use collection expression for empty parameters for `FormUrlEncodedContent`.

Simplify code
