src/TodoApp/Pages/Shared/_Layout.cshtml

Add hr tag that went missing in #3.

Add missing hr tag

---

global.json
src/TodoApp/TodoApp.csproj
tests/TodoApp.Tests/TodoApp.Tests.csproj

Update to preview 6 of .NET 6.

Update to .NET 6 preview 6

---

README.md
src/TodoApp/gulpfile.js

* Do not recompile the TypeScript every time there's a build, as otherwise it slows things down a lot when doing C# edits when Visual Studio keeps re-building.
* Add badge to open the repo in Visual Studio Code.

Port minimal actions changes

---

.github/workflows/update-dotnet-sdk.yml

Disable the SDK update until back on non-daily builds.

Disable scheduled SDK updates

---

.github/workflows/build.yml
.gitignore
build.ps1
tests/TodoApp.Tests/TodoApp.Tests.csproj

Add code coverage to the sample's tests.

Add code coverage

---

README.md

* Add a link to daily .NET SDK builds.
* Reword a sentence.
* Move sentence to a note.

Content tweaks

---

NuGet.config

It should have been removed in #84.

Remove roslyn prerelease feed

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.vscode/extensions.json

Add a configuration file for the devcontainer so that the Playwright CLI is installed.

Better support codespaces

---

.devcontainer/Dockerfile

Follow guidance to reduce/remove errors/warnings that aren't an issue.
See https://code.visualstudio.com/docs/remote/containers-advanced#_reducing-dockerfile-build-warnings.

Reduce Dockerfile warnings

---

global.json
src/TodoApp/TodoApp.csproj
tests/TodoApp.Tests/TodoApp.Tests.csproj

Update to the latest .NET 6 RC1 SDK daily build.

Update .NET SDK

---

global.json
src/TodoApp/TodoApp.csproj
tests/TodoApp.Tests/TodoApp.Tests.csproj

* Update to the latest build of the .NET 6 RC1 SDK.
* Update to the latest version of Swashbuckle.AspNetCore.

Update SDK and NuGet packages

---

src/TodoApp/gulpfile.js

Add watch task

---

src/TodoApp/Program.cs

Remove workaround for issue that was fixed in RC1.

Remove workaround

---

tests/TodoApp.Tests/LoopbackOAuthEvents.cs
tests/TodoApp.Tests/RemoteAuthorizationEventsFilter.cs
tests/TodoApp.Tests/TodoAppFixture.cs

Use a custom `OAuthEvents` class and move the loopback implementation there.

Use custom OAuthEvents class

---

src/TodoApp/ApiEndpoints.cs
src/TodoApp/AuthenticationEndpoints.cs
src/TodoApp/Program.cs

* Change the `Module` suffix to `Endpoints`.
* Rename incorrect parameter.
* Move the services for the API into an extension method.

Minor refactoring

---

NuGet.config
README.md
global.json
src/TodoApp/TodoApp.csproj
tests/TodoApp.Tests/TodoApp.Tests.csproj

Use the final RTM version of .NET 6.

Update to .NET 6

---

README.md

Remove link that's no longer rendered.

Remove redundant link

---

tests/TodoApp.Tests/UITests.cs

Use the `BrowserType` constants for the browser names.

Use BrowserType constants

---

build.ps1
tests/TodoApp.Tests/TodoApp.Tests.csproj

Add GitHubActionsTestLogger for use with dotnet test.

Add GitHubActionsTestLogger

---

.github/workflows/build.yml
tests/TodoApp.Tests/BrowserFixture.cs
tests/TodoApp.Tests/BrowserFixtureOptions.cs

Support capturing traces for UI tests.

Capture Playwright traces

---

.devcontainer/Dockerfile
.github/workflows/build.yml
tests/TodoApp.Tests/TodoApp.Tests.csproj
tests/TodoApp.Tests/UITests.cs

Remove the Playwright global tool and use the built-in installer program instead.

Remove Playwright global tool

---

src/TodoApp/Data/TodoRepository.cs

Add a new line after the namespace.

Fix formatting

---

src/TodoApp/TodoApp.csproj

Use `npm ci` in GitHub Actions.

Use npm ci

---

src/TodoApp/package-lock.json
src/TodoApp/package.json

Remove explicit dependency on `@types/node`.

Remove @types/node

---

src/TodoApp/.eslintignore
src/TodoApp/package.json

Move `.eslintignore` to `package.json`.

Remove .eslintignore

---

.github/workflows/build.yml

Reverts martincostello/dotnet-minimal-api-integration-testing#875

Downgrade codecov/codecov-action from 4 to 3

---

.vscode/launch.json
.vsconfig
README.md
build.ps1
global.json
src/TodoApp/ApiEndpoints.cs
src/TodoApp/Data/TodoContext.cs
src/TodoApp/Data/TodoRepository.cs
src/TodoApp/Services/TodoService.cs
src/TodoApp/TodoApp.csproj
startvscode.cmd
tests/TodoApp.Tests/ApiTests.cs
tests/TodoApp.Tests/BrowserFixture.cs
tests/TodoApp.Tests/BrowserStackLocalOptions.cs
tests/TodoApp.Tests/BrowserStackLocalService.cs
tests/TodoApp.Tests/HttpRequestInterceptionFilter.cs
tests/TodoApp.Tests/RemoteAuthorizationEventsFilter.cs
tests/TodoApp.Tests/TodoApp.Tests.csproj
tests/TodoApp.Tests/TodoPage.cs
tests/TodoApp.Tests/UITests.cs

Update to ASP.NET Core 8

---

.github/workflows/build.yml
.github/workflows/lint.yml

Fix conflicting artifact names.

Fix conflicts

---

tests/TodoApp.Tests/UITests.cs

Use `TheoryData<T>` instead of `IEnumerable<object[]>`.

Use TheoryData<T>

---

src/TodoApp/Program.cs
src/TodoApp/Properties/launchSettings.json
src/TodoApp/TodoApp.csproj

Replace Swashbuckle with NSwag.

Migrate to NSwag

---

tests/TodoApp.Tests/TodoApp.Tests.csproj

Bump Microsoft.Playwright to 1.42.0.

Bump Microsoft.Playwright

---

tests/TodoApp.Tests/TodoApp.Tests.csproj

Refactor how code coverage is reported in GitHub step summaries.

Refactor coverage report markdown

---

src/TodoApp/package-lock.json
src/TodoApp/package.json

Update obsolete linter rule

---

.editorconfig

Disable the IDE0058 style warning as it's creating lots of noise.

Disable IDE0058

---

src/TodoApp/package.json

Remove obsolete eslint indentation rule and use recommended replacement.

Update obsolete eslint rule

---

.github/workflows/build.yml
.github/workflows/code-scan.yml

- Add a workflow to run CodeQL.
- Add setup-node to build.

Add CodeQL

---

.github/workflows/lint.yml

Simplify the container tag for actionlint.

Simplify tag

---

.github/workflows/codeql.yml

- Add CodeQL analysis for GitHub Actions.
- Refactor permissions.
- Add overall job/status for all languages.
- Standardize workflow with other repos.

Add CodeQL analysis for GitHub Actions

---

.github/workflows/build.yml

Resolves https://github.com/martincostello/dotnet-minimal-api-integration-testing/security/code-scanning/292.

Add workflow permissions

---

.github/workflows/build.yml
.gitignore
build.ps1
tests/TodoApp.Tests/TodoApp.Tests.csproj

Use Codecov's test analytics feature.

Add test analytics

---

src/TodoApp/Pages/Home/Index.cshtml
src/TodoApp/Pages/Shared/_Layout.cshtml
src/TodoApp/package-lock.json
src/TodoApp/package.json
src/TodoApp/wwwroot/swagger-ui/index.html

- Upgrade to Bootstrap 5.
- Upgrade to swagger-ui v5.21.0.

Update to Bootstrap 5
